sudo: required
services:
  - docker

before_install:
  - docker build -t kamrade/docker-react-sandbox -f Dockerfile.dev .

script:
  - docker run kamrade/docker-react-sandbox npm run test -- --coverage
